dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "ci: release {{crate_name}} dev version {{version}}"
push = false
tag = false
verify = true
consolidate-pushes = true
sign-commit = true
pre-release-commit-message = "ci: crate release {{crate_name}} version {{version}}"
pre-release-replacements = [
  {file="README.md", min=0, search="= \".*\"", replace="= \"{{version}}\""},
  {file="CHANGELOG.md", min=0, search="## unreleased", replace="## {{version}} - {{date}}"},
]
