name: Nightly
on:
  pull_request:
  push:
  schedule:
    - cron:  '0 1 * * *' # https://cron.help/#0_1_*_*_*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:597fd3f89cfa198d9c3efc19599a3717673934bf4e23eee45be035203297cb59

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
            /root/.cargo/bin/
            /root/.cargo/registry/index/
            /root/.cargo/registry/cache/
            /root/.cargo/git/db/
            target
          key: ${{ runner.os }}-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-cache-

      - id: build
        run: ./gradlew build

  test:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:597fd3f89cfa198d9c3efc19599a3717673934bf4e23eee45be035203297cb59

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
            /root/.cargo/bin/
            /root/.cargo/registry/index/
            /root/.cargo/registry/cache/
            /root/.cargo/git/db/
            target
          key: ${{ runner.os }}-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-cache-

      - id: test
        run: ./gradlew test
